<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="3" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="13735" started-at="2014-04-13T07:33:16Z" finished-at="2014-04-13T07:33:29Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="13735" started-at="2014-04-13T07:33:16Z" finished-at="2014-04-13T07:33:29Z">
      <class name="com.example.tests.TestFolderCreation">
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.example.tests.TestFolderCreation@ced6e2]" name="setUp" is-config="true" duration-ms="24" started-at="2014-04-13T10:33:16Z" finished-at="2014-04-13T10:33:16Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="testFolderCreation()[pri:0, instance:com.example.tests.TestFolderCreation@ced6e2]" name="testFolderCreation" duration-ms="3982" started-at="2014-04-13T10:33:16Z" finished-at="2014-04-13T10:33:20Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testFolderCreation -->
        <test-method status="PASS" signature="testFoldersWithSameNameCreation()[pri:0, instance:com.example.tests.TestFolderCreation@ced6e2]" name="testFoldersWithSameNameCreation" duration-ms="3382" started-at="2014-04-13T10:33:20Z" finished-at="2014-04-13T10:33:23Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testFoldersWithSameNameCreation -->
        <test-method status="FAIL" signature="testVariousFoldersCreation()[pri:0, instance:com.example.tests.TestFolderCreation@ced6e2]" name="testVariousFoldersCreation" duration-ms="6325" started-at="2014-04-13T10:33:23Z" finished-at="2014-04-13T10:33:29Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[
Expected: <Folders [[Persons, newfolder, newfolder3, newfolder2]]]]><![CDATA[>
     but: was <Folders [[Persons, newfolder, newfolder3, newfolder1, newfolder2]]><![CDATA[]]]]><![CDATA[>]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: 
Expected: <Folders [[Persons, newfolder, newfolder3, newfolder2]]]]><![CDATA[>
     but: was <Folders [[Persons, newfolder, newfolder3, newfolder1, newfolder2]]]]><![CDATA[>
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:8)
	at com.example.tests.TestFolderCreation.testVariousFoldersCreation(TestFolderCreation.java:31)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testVariousFoldersCreation -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.example.tests.TestFolderCreation@ced6e2]" name="tearDown" is-config="true" duration-ms="0" started-at="2014-04-13T10:33:29Z" finished-at="2014-04-13T10:33:29Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.example.tests.TestFolderCreation -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
