<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="HP-4540S" name="com.example.tests.ContactRemovalTest" tests="1" failures="0" timestamp="24 Mar 2014 13:35:40 GMT" time="9.564" errors="1">
  <testcase name="deleteSomeContact" time="9.564" classname="com.example.tests.ContactRemovalTest">
    <error type="java.lang.AssertionError" message="Lists differ at element [2]: ContactData [firstname=testdata-1307421519, lastname=testdata1028316528] != ContactData [firstname=testdata-401959705, lastname=testdata1855694608] expected [ContactData [firstname=testdata-1307421519, lastname=testdata1028316528]] but found [ContactData [firstname=testdata-401959705, lastname=testdata1855694608]]">
      <![CDATA[java.lang.AssertionError: Lists differ at element [2]: ContactData [firstname=testdata-1307421519, lastname=testdata1028316528] != ContactData [firstname=testdata-401959705, lastname=testdata1855694608] expected [ContactData [firstname=testdata-1307421519, lastname=testdata1028316528]] but found [ContactData [firstname=testdata-401959705, lastname=testdata1855694608]]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:549)
	at org.testng.Assert.assertEquals(Assert.java:514)
	at com.example.tests.ContactRemovalTest.deleteSomeContact(ContactRemovalTest.java:35)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- deleteSomeContact -->
</testsuite> <!-- com.example.tests.ContactRemovalTest -->
